### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlexeyPytsel** [EasyDonate/EasyPayments#1]
[21:06:54 ERROR]: [EasyPayments] An unexpected error was occurred! 
[21:06:54 WARN]: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@1b1dbf1 rejected from java.util.concurrent.ThreadPoolExecutor@59d7d04d[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 2] 
[21:06:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057) 
[21:06:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827) 
[21:06:54 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) 
[21:06:54 WARN]:        at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:687) 
[21:06:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1778) 
[21:06:54 WARN]:        at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2001) 
[21:06:54 WARN]:        at ru.easydonate.easypayments.task.PaymentsQueryTask.doQuery(PaymentsQueryTask.java:95) 
[21:06:54 WARN]:        at ru.easydonate.easypayments.task.PaymentsQueryTask.run(PaymentsQueryTask.java:81) 
[21:06:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by SoKnight** [comment]
Спасибо, исправлено в **2.0.8**.
